version: "2"
services:
  data:
    image: debian:9
    volumes:
      - ./:/var/www/default/
  buffer:
    image: redis:3.2
    tty: true
    stdin_open: true
    restart: always
    command: redis-server --requirepass ${BUFFER_PASSWORD}
    ports:
      - "6379:6379"
  queue:
    image: php:7.1-fpm
    tty: true
    stdin_open: true
    restart: always
    command: php /var/www/default/bin/console app:queue
    depends_on:
      - data
      - buffer
    volumes_from:
      - data
    env_file:
      - .env
