imports:
  - { resource: parameters.yml }
  - { resource: services.yml }

parameters:
  app.discord_hooks:
    survival-eu:
      id: %discord_id_survival_eu%
      token: %discord_token_survival_eu%
    endless-eu:
      id: %discord_id_endless_eu%
      token: %discord_token_endless_eu%
    survival-na:
      id: %discord_id_survival_na%
      token: %discord_token_survival_na%

framework:
  secret: %framework_secret%
  translator:
    fallbacks: [en]

snc_redis:
  clients:
    default:
      type: predis
      alias: default
      dsn: %buffer_dsn%
      options:
        read_write_timeout: 0

csa_guzzle:
  clients:
    default:
      lazy: true
      config:
        base_uri: 'https://discordapp.com/api/webhooks/'
        options:
          headers:
            Content-Type: 'application/json'
      middleware: ['rate_limit']
