imports:
  - { resource: parameters.yml }
  - { resource: services.yml }

parameters:
  app.discord_hooks:
    eu-survival:
      id: %discord_id_public%
      token: %discord_token_public%
    eu-endless:
      id: %discord_id_group%
      token: %discord_token_group%

framework:
  secret: %framework_secret%
  translator:
    fallbacks: [en]

snc_redis:
  clients:
    default:
      type: predis
      alias: default
      dsn: %buffer_dsn%
      options:
        read_write_timeout: 0

csa_guzzle:
  clients:
    default:
      lazy: true
      config:
        base_uri: 'https://discordapp.com/api/webhooks/'
        options:
          headers:
            Content-Type: 'application/json'
      middleware: ['rate_limit']
